### ISSUE TITLE
后台的代码

### ISSUE THREAD

**Issue by timuyishijian** [yeild/WeChatAppletDemo#1]
这样看不到演示效果，后台代码可以给一个吗？

**Comment by zqbxrambo** [comment]
你好，请问有server的代码么？好像没有找到呢。可否提供一下server代码？

**Comment by yeild** [comment]
@timuyishijian  @zqbxrambo 你好，因为后台代码比较简单，就没有单独建项目，直接提交在了server分支上，可以选择切换分支后下载zip包，或者clone两份项目然后切一个到server分支上-0 0
